apiVersion: v2
name: wa-dyn-agent-prod
version: 10.2.4
appVersion: 10.2.4.00
description: Helm chart for configuring IBM Workload Automation Agent.
keywords:
- Commercial
- amd64
- Workload Scheduler
- Workload Automation
- Automation
- DevOps
kubeVersion: '>=1.14.0 || >=1.14.0-0'
maintainers:
- name: IBM Workload Automation