# *******************************************************************************
# Licensed Materials - Property of HCL
# (c) Copyright HCL Technologies Ltd. 2023. All Rights Reserved.
# 
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# *******************************************************************************
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aida-email.fullname" . }}
  labels:
    {{- include "aida-email.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aida-email.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aida-email.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "aida-email.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false     
            capabilities:
              drop:
              - ALL
          env:          
            - name: LOG_LEVEL
              value: {{ .Values.global.aidaEngineLogLevel | quote }}
            - name: SMTP_SERVER
              value: {{ .Values.smtpServer | quote }} 
            - name: SMTP_PORT
              value: {{ .Values.smtpPort | quote }}
            - name: SENDER_MAILID
              value: {{ .Values.senderEmailId | quote }}
            - name: SENDER_MAILPWD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.senderEmailPwdSecretName }}
                  key: EMAIL_PASSWORD
            - name: RECIPIENT_MAILIDS
              value: {{ .Values.recipientMailIds | quote }}
            - name: REDIS_HOST
              value: {{ include "aida-redis.fullname" . | quote }}
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PSWD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.redisPwdSecretName }}
                  key: REDIS_PASSWORD
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
