# *******************************************************************************
# Licensed Materials - Property of HCL
# (c) Copyright HCL Technologies Ltd. 2023. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# *******************************************************************************
apiVersion: v1
kind: Secret
metadata:
  name: email-pwd-secret
type: Opaque
data:
  EMAIL_PASSWORD: c210cFBhc3N3b3Jk