####################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2021. All rights reserved.
#
# * Trademark of HCL Technologies Limited
####################################################################
{{ $waUserName := include "wa.fileproxy.waUser" .}}
{{ $serviceAccountName:= .Values.global.serviceAccountName | default $waUserName }}
{{- if not ( .Values.global.serviceAccountName ) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.serviceAccountName | default $waUserName }}
  labels:
{{ include "wa-fileproxy-prod.labels" . | indent 4 }}
imagePullSecrets:
- name: sa-{{ .Release.Namespace }}
{{- end }}