####################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2020. All rights reserved.
#
# * Trademark of HCL Technologies Limited
####################################################################
{{- if or ( not .Values.agent.dynamic.useCustomizedCert ) ( not .Values.agent.enableJWT) }} 
{{- include "wa.init" (list . "waagent") }}
{{ $statefulSetName := include "wa.fullName" . }}
{{- if .Capabilities.APIVersions.Has "cert-manager.io/v1"}}
apiVersion: cert-manager.io/v1
{{- else if .Capabilities.APIVersions.Has "certmanager.k8s.io/v1"}}
apiVersion: certmanager.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "cert-manager.io/v1alpha2" }}
apiVersion: cert-manager.io/v1alpha2
{{- else if .Capabilities.APIVersions.Has "certmanager.k8s.io/v1alpha1"}}
apiVersion: certmanager.k8s.io/v1alpha1
{{- end }}
kind: Certificate
metadata:
  name: {{ $statefulSetName }}
  labels:
{{ include "wa.dyn-agent.labels" . | indent 4 }}
  #annotations:
    #"helm.sh/hook": pre-install
    #"helm.sh/hook-delete-policy": hook-failed
spec:
  secretName: {{ .Values.agent.dynamic.certSecretName | quote }}
  duration: {{ .Values.agent.dynamic.certDuration}} # 90d
  renewBefore: {{ .Values.agent.dynamic.certRenewBefore}} # 15d
{{- if or ( .Capabilities.APIVersions.Has "cert-manager.io/v1" ) ( .Capabilities.APIVersions.Has "certmanager.k8s.io/v1" ) }}
  subject:
    organizations:
      - IBM
{{- else if or ( .Capabilities.APIVersions.Has "certmanager.k8s.io/v1alpha1" ) ( .Capabilities.APIVersions.Has "cert-manager.io/v1alpha2" ) }}
  organization:
  - IBM
{{- end }}
  commonName: waagent
  isCA: false
{{- if or ( .Capabilities.APIVersions.Has "certmanager.k8s.io/v1alpha1" ) ( .Capabilities.APIVersions.Has "cert-manager.io/v1alpha2" ) }}
{{- if not ( .Capabilities.APIVersions.Has "cert-manager.io/v1" )  }}
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
{{- end }}
{{- end }}
  usages:
    - server auth
    - client auth
  dnsNames:
  - waagent
{{- if or ( .Capabilities.APIVersions.Has "cert-manager.io/v1alpha2") ( .Capabilities.APIVersions.Has "cert-manager.io/v1")  }}
  privateKey:
    rotationPolicy: Always
{{- if ( .Capabilities.APIVersions.Has "cert-manager.io/v1")  }}
    size: 2048
    algorithm: RSA
    encoding: PKCS1
{{- end }}
{{- end }}
  issuerRef:
    name: wa-ca-issuer
    kind: Issuer
{{- end }}
