####################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2020. All rights reserved.
#
# * Trademark of HCL Technologies Limited
####################################################################
{{- if not .Values.agent.dynamic.useCustomizedCert }} 
{{- include "wa.init" (list . "waagent") }}
{{ $statefulSetName := include "wa.fullName" . }}
{{- if .Capabilities.APIVersions.Has "cert-manager.io/v1alpha2" }}
apiVersion: cert-manager.io/v1alpha2
{{- else }}
apiVersion: certmanager.k8s.io/v1alpha1
{{- end }}
kind: Certificate
metadata:
  name: {{ $statefulSetName }}
  labels:
{{ include "wa.dyn-agent.labels" . | indent 4 }}
  #annotations:
    #"helm.sh/hook": pre-install
    #"helm.sh/hook-delete-policy": hook-failed
spec:
  secretName: {{ .Values.agent.dynamic.certSecretName | quote }}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  organization:
  - IBM
  commonName: waagent
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
    - server auth
    - client auth
  dnsNames:
  - waagent
 {{- if .Capabilities.APIVersions.Has "cert-manager.io/v1alpha2" }}
  privateKey:
    rotationPolicy: Always
 {{- end }}
  issuerRef:
    name: wa-ca-issuer
    kind: Issuer
{{- end }}
