{{- if .Values.agent.dynamic.useSaaSConfig }} 
####################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2020. All rights reserved.
#
# * Trademark of HCL Technologies Limited
####################################################################
{{- include "wa.init" (list . "waagent") }}
{{ $statefulSetName := include "wa.fullName" . }}
{{- $agent_config_url:= printf "https://%s/SaaSDownloadProxy/DownloadProxy/agent/config.zip?subscriptionID=%s&ctrlCallback=%s" .Values.agent.dynamic.saasConfig.engine .Values.agent.dynamic.saasConfig.subscriptionID .Values.agent.dynamic.saasConfig.controllerHostname }}
apiVersion: v1
kind: Secret
metadata:
  name: da-secret-saas
  labels:
{{ include "wa.labels" . | indent 4 }}
type: Opaque
data:
  agent_config_url: {{ $agent_config_url | squote |  b64enc }}
  userId: {{ .Values.agent.dynamic.saasConfig.userID | squote | b64enc}} 
  password: {{ .Values.agent.dynamic.saasConfig.password | squote | b64enc}}
{{- end }}