####################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2021. All rights reserved.
#
# * Trademark of HCL Technologies Limited
####################################################################
global:
  license: "not accepted"
  serviceAccountName:
replicaCount: 1
image:
  repository: cp.icr.io/cp/ibm-workload-automation-fileproxy
  tag: 10.1.0.00.20220722
  pullPolicy: Always
nameOverride: ""
fullnameOverride: ""
pwdSecretName: wa-pwd-secret-fp
fileProxy:
  certSecretName: wa-fileproxy-cert
  useCustomizedCert: false
  containerDebug: false
  port: 44444
  route:
    enabled: false
  exposeServiceType: Ingress
  exposeServiceAnnotation: {}
podAnnotations: {}
podSecurityContext: {}
  # fsGroup: 2000
securityContext: 
   capabilities:
     drop:
     - ALL
   readOnlyRootFilesystem: false
   runAsNonRoot: true
   runAsUser: 999
ingress:
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: 
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
