####################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2020. All rights reserved.
#
# * Trademark of HCL Technologies Limited
####################################################################
{{ $waUserName := include "wa.agent.waUser" .}}
{{ $serviceAccountName:= .Values.global.serviceAccountName | default $waUserName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.serviceAccountName | default $waUserName }}
  labels:
{{ include "wa.zcentric-agent.labels" . | indent 4 }}
imagePullSecrets:
- name: sa-{{ .Release.Namespace }}
