####################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2022. All rights reserved.
#
# * Trademark of HCL Technologies Limited
####################################################################
{{- include "wa.init" (list . "waagent") }}
{{ $dataPvcName := .Values.persistence.dataPVC.name }}
{{ $statefulSetName := include "wa.fullName" . }}
{{ $persistentVolumeClaimName := include "wa.volumeClaimTemplateName" (list . $dataPvcName) }}
{{ $fullName := include "wa.fullName" . }}
{{ $serviceName := include "waAgt.ServiceName" . }}
{{ $waUserName := include "wa.agent.waUser" .}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $statefulSetName }}
  labels:
{{ include "wa.zcentric-agent.labels" . | indent 4 }}
spec:
  updateStrategy: 
    type: RollingUpdate
  serviceName: {{ $serviceName }}-h
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "wa.appName" . }}"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
{{ include "wa.zcentric-agent.labels" . | indent 8 }}
        affinity: wa-agent
      annotations:
      {{- if eq (.Values.licenseType | upper )  "PVU" }} 
{{ include "wa.pvu.metering" . | indent 8 }} 
      {{- else }}
{{ include "wa.metering" . | indent 8 }}      
      {{- end }}
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false      
      securityContext:
        runAsNonRoot: true
      {{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1") }} 
        runAsUser: {{ .Values.runAsUser | default 999 }}
        fsGroup: {{ .Values.fsGroupId | default 999 }}  
      {{- end }}
        supplementalGroups: [{{ .Values.supplementalGroupId | default 999 }}]
      serviceAccountName: {{ .Values.global.serviceAccountName | default $waUserName }}               
      affinity:
        #schedule pod on different nodes when possible
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: affinity
                  operator: In
                  values:
                  - wa-agent
              topologyKey: kubernetes.io/hostname
{{ include "wa.nodeaffinity" . | indent 8 }} 
{{- if .Values.agent.nodeAffinityRequired }} 
{{ .Values.agent.nodeAffinityRequired | toYaml | trimSuffix "\n" | indent 14 -}}
{{- end }}  
{{- if .Values.persistence.enabled }}                
      initContainers:
      - name: init-config
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: {{ $persistentVolumeClaimName }}
          mountPath: /tmp/data
        command: [/opt/wautils/wa_populate_volume.sh]
        args: ["-s /home/wauser -d /tmp/data"] 
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false     
          capabilities:
            drop:
            - ALL   
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}                  
      containers:
      - name: {{ .Chart.Name }}
        readinessProbe:
          exec:
            command:
            - /opt/wautils/wa_probe.sh
            - agent
            - readiness
          initialDelaySeconds: 200
          failureThreshold: 3
          periodSeconds: 60
        livenessProbe:
          exec:
            command:
            - /opt/wautils/wa_probe.sh
            - agent
            - liveness
          initialDelaySeconds: {{ default 60 .Values.agent.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: 10
          failureThreshold: 3
          periodSeconds: 60
        env:
        - name: LICENSE
          value: {{ .Values.global.license | quote }}
        - name: LANG
          value: {{ default "en" .Values.global.language }}
        - name: WA_DEBUG
          value: {{ .Values.agent.containerDebug | quote }}        
        - name: AGT_NAME
          value: {{ .Values.agent.name | quote }}
        - name: WA_IS_KUBE
          value: "true"          
        - name: WA_DEBUG_SCRIPTS
          value: "false"  
        - name: WA_USER_ENGINE
          valueFrom:
            secretKeyRef:
              name: {{ include "wa.fullName" . }}-secret
              key: WA_USER_ENGINE
              optional: true  
        - name: WA_USER_ENGINE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "wa.fullName" . }}-secret
              key: WA_USER_ENGINE_PASSWORD
              optional: true  
        - name: SSL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "wa.fullName" . }}-secret
              key: SSL_PASSWORD
              optional: true       
        {{- if .Values.agent.tz }}
        - name: TZ
          value: {{ .Values.agent.tz | quote }}
        {{- end }}           
        {{- if .Values.agent.zcentric.server.mdmhostname }}  
        - name: SERVERHOSTNAME
          value: {{ .Values.agent.zcentric.server.mdmhostname | quote }}  
        - name: SERVERPORT
          value: {{ .Values.agent.zcentric.server.port | quote }}
        {{- else }}  
        - name: SERVERHOSTNAME
          value: {{ template "waAgt.ServiceName" . }} 
        - name: SERVERPORT
          value: "31116"        
        {{- end }}  
        {{- if .Values.agent.zcentric.zconn }}
        - name: ZCONN_URL
          value: {{ .Values.agent.zcentric.zconn| quote }}
        {{- end }}
        # Z Agents do not support Backup master and Dynamic Pools 
        # {{- if .Values.agent.zcentric.server.bkmhostname }}
        # - name: BKMSERVERHOSTNAME
        #   value: {{ .Values.agent.zcentric.server.bkmhostname | quote }}
        # {{- end }}
        # {{- if .Values.agent.zcentric.pools }}
        # - name: POOLS
        #   value: {{ .Values.agent.zcentric.pools | quote }}
        # {{- end }}   
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false     
          capabilities:
            drop:
            - ALL          
        resources:
{{ toYaml .Values.resources | indent 12 }}
{{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: {{ $persistentVolumeClaimName }}
          mountPath: /home/wauser
          subPath: wauser
        - name: cert-bind-volume
          mountPath: /opt/wautils/certs
        - name: {{ include "wa.fullName" . }}-agent-scripts-volume
          mountPath: /opt/wautils/custom_scripts
{{- if ne (len .Values.persistence.extraVolumeMounts) 0 }}
{{ toYaml .Values.persistence.extraVolumeMounts | indent 8 }}
{{- end }}
      volumes:
      - name: cert-bind-volume
        secret:
          defaultMode: 0664
          secretName: {{ .Values.agent.zcentric.certSecretName }}
      - name: {{ include "wa.fullName" . }}-agent-scripts-volume
        configMap:
          name: {{ include "wa.fullName" . }}-agent-scripts
          defaultMode: 0777
          optional: true
{{- if ne (len .Values.persistence.extraVolumes) 0 }}
{{ toYaml .Values.persistence.extraVolumes | indent 6 }}
{{- end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ $persistentVolumeClaimName }}
      labels: 
{{ include "wa.zcentric-agent.labels" . | indent 8 }} 
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.persistence.dataPVC.size | quote }}
      {{- if .Values.persistence.useDynamicProvisioning }}
      # if present, use the storageClassName from the values.yaml, else use the
      # default storageClass setup by kube Administrator
      # setting storageClassName to nil means use the default storage class
      storageClassName: {{ default nil .Values.persistence.dataPVC.storageClassName | quote }}
      {{- else }}
      # bind to an existing pv.
      # setting storageClassName to "" disables dynamic provisioning 
      storageClassName: ""
        {{- if .Values.persistence.dataPVC.selector.label }}
      # use selectors in the binding process
      selector:
        matchLabels:
          {{ .Values.persistence.dataPVC.selector.label }}: {{ .Values.persistence.dataPVC.selector.value }}
        {{- end }}      
      {{- end }}
{{- end }}
