####################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2022. All rights reserved.
#
# * Trademark of HCL Technologies Limited
####################################################################
{{- include "wa.init" (list . "waagent") }}
{{ $fullName := include "waAgt.ServiceName" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-h
  labels:
{{ include "wa.zcentric-agent.labels" . | indent 4 }}
spec:
  clusterIP: None
  ports:
  - name: ita-port
    protocol: TCP
    port: 31118
    targetPort: 3118
  selector:
    app.kubernetes.io/name: "{{ include "wa.appName" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}" 