# *******************************************************************************
# Licensed Materials - Property of HCL
# (c) Copyright HCL Technologies Ltd. 2022. All Rights Reserved.
# 
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# *******************************************************************************
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aida-nginx.fullname" . }}
  labels:
    {{- include "aida-nginx.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aida-nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aida-nginx.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "aida-nginx.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false     
            capabilities:
              drop:
              - ALL
          env:          
              - name: CLIENT_SECRET
                value: "AIDA-SECRET"
              - name: DWC_PUBLIC_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.waConsoleCertSecretName }}
                    key: tls.crt
              - name: KEYCLOAK_URL
                value: "http://127.0.0.1" 
              - name: UI_URL
                value: "https://{{ include "aida-ui.fullname" . }}:9000"
              - name: PROPHET_URL
                value: "http://{{ include "aida-predictor.fullname" . }}:5000"
              - name: ALERT_URL
                value: "http://{{ include "aida-ad.fullname" . }}:5000"
              - name: LICENSE
                value: {{ .Values.global.license | quote }}  
          ports:
            - name: https
              containerPort: 9432
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: https
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /
              port: https
              scheme: HTTPS
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
