{{- if .Capabilities.APIVersions.Has "route.openshift.io/v1" -}}
{{- if or (.Values.routes.enabled) (eq (.Values.exposeServiceType | upper )  "ROUTE") }} 
# *******************************************************************************
# Licensed Materials - Property of HCL
# (c) Copyright HCL Technologies Ltd. 2022. All Rights Reserved.
# 
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# *******************************************************************************
{{ $fullName := include "aida-nginx.fullname" . }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ $fullName }}
  labels:
{{ include "aida-nginx.labels" . | indent 4 }}
  annotations:
    openshift.io/host.generated: 'true'
    haproxy.router.openshift.io/cookie_name: {{ $fullName }}-affinity-cookie
spec:
  host: 
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
  port:
    targetPort: https
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
status:
  ingress:
    - host: 
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
      wildcardPolicy: None
{{- end }}
{{- end }}
