####################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2021. All rights reserved.
#
# * Trademark of HCL Technologies Limited
####################################################################

global:
  language: "en"
  # set to "accept" to accept the license
  license: "not accepted"
  # geographical data
  certManager:
    organization: "IBM"
    locality: "Rome"
    province: "Lazio"
    country: "IT"
  serviceAccountName: wauser
  imagePullSecrets: []
  useClusterRole: false
  aidaEngineLogLevel: "INFO"
  redisPwd: "default"
  defaultShardCount: 1
  
  enablePrometheus: true
  routeType: "passthrough" # passthrough | reencrypt
  customPluginImageName: ""
  pluginImageName: "cp.icr.io/cp/ibm-workload-automation-plugins:10.2.8.00.20260727"
  configPlugins: ""
  
  customLabels:
    - name: "environment"
      value: "prod"
replicaCount: 1
ddmCommonName: "waddm"
agentextCommonName: "waagent"
customDnsOnly: false
addCustomDns: false
customDns: []
issuerName: "wa-ca-issuer"
issuerKind: "Issuer"
issuerGroup: "cert-manager.io"
loadBalancerIP: ""
licenseType: "PERJOB"
runAsUser: 999
fsGroupId: 999
supplementalGroupId: null

image:
  repository: "cp.icr.io/cp/ibm-workload-automation-ddm"
  tag: "10.2.8.00.20260727"
  pullPolicy: "Always"

ddm:
  hostname: ""
  mdmHostname: ""
  mdmPort: "31116"
  masterName: ""
  ddmMaster: "" #MDM Workstation name
  waServerHost: ""
  domain: "DYNAMICDM"
  dwbName: "WA_DWB_DDM"
  
  publicHostname: ""
  publicPort: "31116"
  waServiceDomain: ""
  
  jobLog:
    type: "memory"
    corePoolSize: 50
  company: "my-company"
  ftaName: ""
  agentName: "WA_SAGT"
  dateFormat: "MM/DD/YYYY"
  startOfDay: "0700"
  timezone: ""
  tz: ""
  createPlan: false
  externalFileProxyEnabled: false
  externalFileProxyURLs: ""
  containerDebug: false
  enableSSO: true
  enableSingleInstaceNetwork: false
  adminGroup: ""
  
  # OpenTelemetry config
  otel_sdk_disabled: true
  otel_traces_exporter: "otlp"
  otel_exporter_otlp_endpoint: "http://localhost:4317"
  otel_exporter_otlp_traces_endpoint: "http://localhost:4317"
  otel_exporter_otlp_protocol: "grpc"
  otel_exporter_otlp_traces_protocol: "grpc"
  
  # Database Config
  db:
    adminUser: "db2inst1"
    hostname: "dbhost"
    alternateHostName: ""
    name: "TWS"
    port: 50000
    alternatePort: ""
    server: ""
    sslConnection: false
    tsLogName: ""
    tsLogPath: ""
    tsName: ""
    tsPath: ""
    tsPlanName: ""
    tsPlanPath: ""
    tsTempName: ""
    tssbspace: ""
    type: "DB2"
    usepartitioning: true
    user: "db2inst1"
    skipCheck: false
    
  licenseServerUrl: ""
  licenseServerId: ""
  pwdSecretName: "wa-pwd-secret"
  libConfigName: ""
  
  readinessProbe:
    initialDelaySeconds: 600
  livenessProbe:
    initialDelaySeconds: 600

  useCustomizedCert: false
  certSecretName: "wa-ddm-cert-secret"
  certDuration: "2160h" # 90d
  certRenewBefore: "360h" # 15d
  routes:
    enabled: true
    hostname: ""
    
  ingress:
    hostname: ""
    className: ""
    secretName: "wa-ddm-ingress-secret"
    enableSSLPassthrough: false

  gatewayApi:
    enabled: true
    skipLibraryCheck: false
    gatewayName: ""
    gatewayNamespace: ""
    parentRefs: []
    hostnames: []
    pathPrefix: "/"
    annotations: {}
    backendConfig: {}
    backendTLSPolicy:
      enabled: true
      caCertificateSecretName: ""
      hostname: ""

  exposeServiceType: "None" # Ingress | LoadBalancer | Route | GatewayAPI | None
  exposeServiceAnnotation: {}
  networkpolicyEgress: {}
  nodeAffinityRequired: {}
resources:
  requests:
    cpu: 1
    memory: "4Gi"
  limits:
    cpu: 4
    memory: "8Gi"
persistence:
  enabled: true
  useDynamicProvisioning: true
  dataPVC:
    name: "data"
    storageClassName: ""
    selector:
      label: ""
      value: ""
    size: "10Gi"
  extraVolumes: []
    # - name: custom-volume-1
    #   configMap:
    #      name: custom-configMap
    #      defaultMode: 0755
  extraVolumeMounts: []
    # - name: custom-volume-1
    #   mountPath: /custom/mount/path-1
    #   readOnly: false

enableBmEventsLogging: false
bmEvents: |-
  OPTIONS=MASTER
  LOGGING=ALL
  CHSCHED=HIGH
  PIPE=/home/wauser/wadata/MAGENT.P
  FILE=/home/wauser/wadata/event.log
  JSON=/home/wauser/wadata/event.json