####################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2021. All rights reserved.
#
# * Trademark of HCL Technologies Limited
####################################################################
{{- if .Values.enableBmEventsLogging }}
{{- include "wa.init" (list . "waserver") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wa.fullName" . }}-bm-events-config
  labels:
{{ include "wa.server.labels" . | indent 4 }}
data:
  BmEvents.conf: |-
{{ .Values.bmEvents | indent 4 }}
{{- end }}