{{- if .Capabilities.APIVersions.Has "route.openshift.io/v1" -}}
{{- if or (.Values.console.routes.enabled) (eq (.Values.console.exposeServiceType | upper )  "ROUTE")  }} 
####################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2019. All rights reserved.
#
# * Trademark of HCL Technologies Limited
####################################################################
{{- include "wa.init" (list . "waconsole") }}
{{ $fullName := include "wa.fullName" . }}
{{ $dwcServiceName := include "wa.fullName" . }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: wa-console-route
  labels:
{{ include "wa.console.labels" . | indent 4 }}
  annotations:
    openshift.io/host.generated: 'true'
    haproxy.router.openshift.io/cookie_name: wa-console-affinity-cookie
spec:
  host: 
  to:
    kind: Service
    name: {{ $dwcServiceName }}
    weight: 100
  port:
    targetPort: https
  tls:
    termination: {{ .Values.global.routeType | default "passthrough" }}
    insecureEdgeTerminationPolicy: None
    {{- if eq (.Values.global.routeType | upper) "REENCRYPT" }}
    {{- $secret := lookup "v1" "Secret" .Release.Namespace "ca-key-pair" }}
    {{- if $secret }}
    {{- if index $secret.data "ca.crt" }}
    destinationCACertificate: |
{{ index $secret.data "ca.crt" | b64dec | indent 4 }}
    {{- else }}
    {{- fail "Secret ca-key-pair existe mais ne contient pas la clé ca.crt" }}
    {{- end }}
    {{- else }}
    {{- fail "Mode reencrypt activé mais secret ca-key-pair n'existe pas dans le namespace" }}
    {{- end }}
    {{- end }}
  wildcardPolicy: None
status:
  ingress:
    - host: 
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
      wildcardPolicy: None
{{- end }}
{{- end }}