apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aida-es.fullname" . }}-config
  labels:
    {{- include "aida-es.labels" . | nindent 4 }}
data:
  opensearch.yml: |
    # ======================== OpenSearch Configuration =========================
    #
    # NOTE: OpenSearch comes with reasonable defaults for most settings.
    #       Before you set out to tweak and tune the configuration, make sure you
    #       understand what are you trying to accomplish and the consequences.
    #
    # The primary way of configuring a node is via this file. This template lists
    # the most important settings you may want to configure for a production cluster.
    #
    # Please consult the documentation for further information on configuration options:
    # https://www.opensearch.org
    #
    # ---------------------------------- Cluster -----------------------------------
    #
    # Use a descriptive name for your cluster:
    #
    # ------------------------------------ Node ------------------------------------
    #
    # Use a descriptive name for the node:
    #
    #cluster.name: my-application
    #
    # ------------------------------------ Node ------------------------------------
    #
    # Use a descriptive name for the node:
    #
    #
    # Add custom attributes to the node:
    #
    #node.attr.rack: r1
    #
    # ----------------------------------- Paths ------------------------------------
    #
    # Path to directory where to store the data (separate multiple locations by comma):
    #
    #path.data: /path/to/data
    #
    # Path to log files:
    #
    #path.logs: /path/to/logs
    #
    # ----------------------------------- Memory -----------------------------------
    #
    # Lock the memory on startup:
    #
    bootstrap.memory_lock: true
    #
    # Make sure that the heap size is set to about half the memory available
    # on the system and that the owner of the process is allowed to use this
    # limit.
    #
    # OpenSearch performs poorly when the system is swapping the memory.
    #
    # ---------------------------------- Network -----------------------------------
    #
    # Set the bind address to a specific IP (IPv4 or IPv6):
    #
    #
    network.host: [_local_, _site_]
    #
    # Set a custom port for HTTP:
    #
    http.port: 9200
    #
    # For more information, consult the network module documentation.
    #
    # --------------------------------- Discovery ----------------------------------
    #
    discovery.type: single-node
    # Pass an initial list of hosts to perform discovery when this node is started:
    # The default list of hosts is ["127.0.0.1", "[::1]"]
    #
    discovery.seed_hosts: ${DISCOVERY_SEED_HOSTS:127.0.0.1,[::1]}
    #
    # Bootstrap the cluster using an initial set of master-eligible nodes:
    #
    cluster.name: aida-es-cluster
    node.name: ${NODE_NAME:node-1}
    node.master: ${NODE_MASTER:true}
    cluster.initial_master_nodes: ${CLUSTER_INITIAL_MASTER_NODES:}
    #
    # For more information, consult the discovery and cluster formation module documentation.
    #
    # ---------------------------------- Gateway -----------------------------------
    #
    # Block initial recovery after a full cluster restart until N nodes are started:
    #
    #gateway.recover_after_nodes: 3
    #
    # For more information, consult the gateway module documentation.
    #
    # ---------------------------------- Various -----------------------------------
    #
    # Require explicit names when deleting indices:
    #
    #action.destructive_requires_name: true
    #---------CONFIG--------#
    plugins.security.ssl.transport.pemcert_filepath: node.pem
    plugins.security.ssl.transport.pemkey_filepath: node-key.pem
    plugins.security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
    plugins.security.ssl.transport.enforce_hostname_verification: false
    plugins.security.ssl.http.enabled: true
    plugins.security.ssl.http.pemcert_filepath: node.pem
    plugins.security.ssl.http.pemkey_filepath: node-key.pem
    plugins.security.ssl.http.pemtrustedcas_filepath: root-ca.pem
    plugins.security.allow_unsafe_democertificates: true
    plugins.security.allow_default_init_securityindex: true
    plugins.security.authcz.admin_dn:
        - CN=kirk,OU=client,O=client,L=test, C=de
    plugins.security.audit.type: internal_opensearch
    plugins.security.enable_snapshot_restore_privilege: false
    plugins.security.check_snapshot_restore_write_privileges: false
    plugins.security.restapi.roles_enabled:
        ["all_access", "security_rest_api_access"]
    plugins.security.system_indices.enabled: true
    plugins.security.system_indices.indices:
        [
            ".opendistro-alerting-config",
            ".opendistro-alerting-alert*",
            ".opendistro-anomaly-results*",
            ".opendistro-anomaly-detector*",
            ".opendistro-anomaly-checkpoints",
            ".opendistro-anomaly-detection-state",
            ".opendistro-reports-",
            ".opendistro-notifications-",
            ".opendistro-notebooks",
            ".opendistro-asynchronous-search-response*",
            ".replication-metadata-store",
        ]
    node.max_local_storage_nodes: 1
    plugins.security.disabled: false
    path.data: /usr/share/opensearch/data/
  jvm.options: |
    ## JVM configuration
    ################################################################
    ## IMPORTANT: JVM heap size
    ################################################################
    ##
    ## You should always set the min and max JVM heap size to the same value. 
    ## Xms represents the initial size of total heap space
    ## Xmx represents the maximum size of total heap space
    -Xms2g
    -Xmx2g
    ################################################################
    ## Expert settings
    ################################################################
    ##
    ## All settings below this section are considered
    ## expert settings. Don't tamper with them unless
    ## you understand what you are doing
    ##
    ################################################################
    ## GC configuration
    #8-13:-XX:+UseConcMarkSweepGC
    #8-13:-XX:CMSInitiatingOccupancyFraction=75
    #8-13:-XX:+UseCMSInitiatingOccupancyOnly
    ## G1GC Configuration
    # NOTE: G1 GC is only supported on JDK version 10 or later
    # to use G1GC, uncomment the next two lines and update the version on the
    # following three lines to your version of the JDK
    # 10-13:-XX:-UseConcMarkSweepGC
    # 10-13:-XX:-UseCMSInitiatingOccupancyOnly
    14-:-XX:+UseG1GC
    14-:-XX:G1ReservePercent=25
    14-:-XX:InitiatingHeapOccupancyPercent=30
    ## JVM temporary directory
    # Commented by me
    #-Djava.io.tmpdir=${ES_TMPDIR}
    ## heap dumps
    # generate a heap dump when an allocation from the Java heap fails
    # heap dumps are created in the working directory of the JVM
    -XX:+HeapDumpOnOutOfMemoryError
    # specify an alternative path for heap dumps; ensure the directory exists and
    # has sufficient space
    #-XX:HeapDumpPath=/var/lib/opensearch
    # specify an alternative path for JVM fatal error logs
    #-XX:ErrorFile=/var/log/opensearch/hs_err_pid%p.log
    ## OpenDistro Performance Analyzer
    #-Dclk.tck=100
    #-Djdk.attach.allowAttachSelf=true
    #-Djava.security.policy=file:///usr/share/opensearch/plugins/opendistro-performance-analyzer/pa_config/es_security.policy
