# This secret is used for the Agent SSL credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ssl-agent-secret
  labels:
{{ include "wa.labels" . | indent 4 }}
type: "Opaque"
{{- $secretName := print .Release.Name "-ssl-agent-secret" }}
{{- $previous := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
data:
  {{- if and $previous (hasKey $previous.data "AGENT_SSL_PASSWORD") }}
  AGENT_SSL_PASSWORD: {{ $previous.data.AGENT_SSL_PASSWORD }}
  {{- else if .Values.waserver.agentSsl.password }}
  AGENT_SSL_PASSWORD: {{ .Values.waserver.agentSsl.password | b64enc | quote }}
  {{- else }}
  AGENT_SSL_PASSWORD: {{ randAlphaNum 8 | b64enc | quote }}
  {{- end }}