# This secret is used to set the initial credentials of the node container.
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ssl-secret
  labels:
{{ include "wa.labels" . | indent 4 }}
type: "Opaque"
{{- $secretName := print .Release.Name  "-ssl-secret"}}
{{- $previous := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
data:
  {{- if $previous }}
  SSL_PASSWORD: {{ $previous.data.SSL_PASSWORD }}
  {{- else }}
  SSL_PASSWORD: {{ randAlphaNum 8 | b64enc | quote }}
  {{- end }}
 