{{- if not .Values.waserver.server.useCustomizedCert }}
# This secret is used to set the initial credentials of the node container.
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ssl-secret
  labels:
{{ include "wa.labels" . | indent 4 }}
type: "Opaque"
{{- $previous := lookup "v1" "Secret" .Release.Namespace  "{{ .Release.Name }}-ssl-secret" }}
data:
  {{- if $previous }}
  SSL_PASSWORD: {{ $previous.data.SSL_PASSWORD }}
  {{- else }}
  SSL_PASSWORD: {{ randAlphaNum 8 | b64enc | quote }}
  {{- end }}
{{- end }}