# *******************************************************************************
# Licensed Materials - Property of HCL
# (c) Copyright HCL Technologies Ltd. 2023. All Rights Reserved.
# 
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# *******************************************************************************
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aida-ad.fullname" . }}
  labels:
    {{- include "aida-ad.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aida-ad.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aida-ad.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "aida-ad.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false     
            capabilities:
              drop:
              - ALL
          env:          
              - name: LOG_LEVEL
                value: {{ .Values.global.aidaEngineLogLevel | quote }}
              - name: ESCONFIG
                value: '["https://admin:admin@{{ include "aida-es.fullname" . }}:9200"]'
              - name: REDIS_HOST
                value: {{ include "aida-redis.fullname" . | quote }}
              - name: REDIS_PORT
                value: "6379"
              - name: REDIS_PSWD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.global.redisPwdSecretName }}
                    key: REDIS_PASSWORD
              - name: AIDA_UI_URL
                value: "https://{{ include "aida-ui.fullname" . }}:9432/"
              - name: WEB_CONCURRENCY
                value: {{ .Values.webConcurrency | quote }}
              - name: PAST_MILLIS
                value: {{ .Values.pastMillis | quote }}
              - name: TOLERANCE_MILLIS
                value: {{ .Values.toleranceMillis | quote }}
              - name: MINIMUM_SEVERITY_FOR_MAIL
                value: {{ .Values.minimumSeverityForMail | quote }}
              - name: HOST_IP
                value: {{ .Values.host_ip | quote }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
