{{- if .Values.serviceAccount.create -}}
# *******************************************************************************
# Licensed Materials - Property of HCL
# (c) Copyright HCL Technologies Ltd. 2022. All Rights Reserved.
# 
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# *******************************************************************************
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aida-exporter.serviceAccountName" . }}
  labels:
    {{- include "aida-exporter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
imagePullSecrets:
- name: sa-{{ .Release.Namespace }}
{{- end }}