####################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2019. All rights reserved.
#
# * Trademark of HCL Technologies Limited
####################################################################
name: wa-console-prod
version: 1.6.2
appVersion: 10.1.0.00
description: Helm chart for configuring IBM Workload Automation.
keywords:
- Commercial
- amd64
- Workload Scheduler
- Workload Automation
- Automation
- DevOps
maintainers:
- name: IBM Workload Automation
kubeVersion: ">=1.14.0 || >=1.14.0-0"
apiVersion: v2
