apiVersion: v2
version: 1.5.14
appVersion: 9.5.0.05
description: Helm chart for configuring IBM Workload Automation.
keywords:
- Commercial
- amd64
- Workload Scheduler
- Workload Automation
- Automation
- DevOps
- ICP
kubeVersion: ">=1.14.0 || >=1.14.0-0"
maintainers:
- name: IBM Workload Automation
name: workload-automation-prod
dependencies:
  - name: wa-server-prod
    version: 1.5.14
    alias: waserver
    condition: waserver.enableServer
  - name: wa-console-prod
    version: 1.5.14
    alias: waconsole
    condition: waconsole.enableConsole
  - name: wa-dyn-agent-prod
    version: 1.5.14
    alias: waagent
    condition: waagent.enableAgent