apiVersion: v2
version: 1.6.2
appVersion: 10.1.0.00
description: Helm chart for configuring IBM Workload Automation.
keywords:
- Commercial
- amd64
- Workload Scheduler
- Workload Automation
- Automation
- DevOps
- ICP
kubeVersion: ">=1.14.0 || >=1.14.0-0"
maintainers:
- name: IBM Workload Automation
name: workload-automation-prod
dependencies:
  - name: wa-server-prod
    version: 1.6.2
    alias: waserver
    condition: waserver.enableServer
  - name: wa-console-prod
    version: 1.6.2
    alias: waconsole
    condition: waconsole.enableConsole
  - name: wa-dyn-agent-prod
    version: 1.6.2
    alias: waagent
    condition: waagent.enableAgent
  - name: wa-fileproxy-prod
    version: 1.6.2
    alias: wafileproxy
    condition: wafileproxy.enableFileProxy
  - name: wa-aida-prod
    version: 1.0.0
    alias: waaida
    condition: waaida.enableAIDA