kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wa-pod-label
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "update", "patch"]
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
  